### ISSUE TITLE
bert+seq2seq的vocab.txt文件

### ISSUE THREAD

**Issue by BillLZD** [saiwaiyanyu/tensorflow-bert-seq2seq-dream-decoder#1]
请问大佬能上传一下bert+seq2seq目录下的vocab.txt这个文件吗，在bert+seq2seq目录下似乎不能再用外面目录生成的vocab.txt文件了，会产生这样的错误：
```
Traceback (most recent call last):
  File "model.py", line 186, in <module>
    train()
  File "model.py", line 21, in train
    args.is_training,
  File "F:\bertSeq\bert-seq2seq-dream-decoder\seq2seq.py", line 88, in __init__
    decoder_input = tf.concat([tf.fill([batch_size, 1], self.tokenizer.vocab["[SEP]"]), main], 1)
KeyError: '[SEP]'
```

**Comment by saiwaiyanyu** [comment]
是 seq2seq-bert 目录下面么？    chinese_L-12_H-768_A-12

**Comment by saiwaiyanyu** [comment]
seq2seq-bert 有说明，需要下载 bert 预训练模型。然后解压，解压后 chinese_L-12_H-768_A-12 里面有 vocab.txt 文件哈。

**Comment by BillLZD** [comment]
找到了，谢谢大佬哈！
